# escape=`

### 1: Build Angular Application ###

FROM node:12.7-alpine AS build-stage
#FROM node:10 AS build-stage
LABEL author="Jawad Hasan"

# Set the working directory inside container
WORKDIR /app

COPY AccountingBook.Web/package*.json /app/

# Install all the dependencies
RUN npm install

#copy source-code to container
COPY AccountingBook.Web/ /app/
COPY nginx-custom.conf/ /app/

#install npm packages and build the angular application
#RUN npm install
RUN npm run build


# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy the build output to replace the default nginx contents.
COPY --from=build-stage /app/wwwroot/ /usr/share/nginx/html

#COPY NGINX Conf
COPY --from=build-stage /app/nginx-custom.conf /etc/nginx/conf.d/default.conf


# Expose port 80
EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]

#docker image build -t accountingui -f ./Dockerfile.ui .
#docker run --rm --name accountingui -p 8000:80 accountingui
